In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score,recall_score,f1_score,confusion_matrix
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv("/content/train.csv")
X = dataset.iloc[:, 2:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
dataset.head(10)

filename  length  chroma_stft_mean  chroma_stft_var  rms_mean  \
0      pop.00072.5.wav   66149          0.464264         0.079744  0.228116   
1     jazz.00038.9.wav   66149          0.254604         0.090115  0.075960   
2    disco.00055.3.wav   66149          0.488070         0.065943  0.119709   
3     rock.00025.9.wav   66149          0.440747         0.071972  0.108535   
4     jazz.00013.4.wav   66149          0.369718         0.090648  0.052010   
5    blues.00054.0.wav   66149          0.482166         0.072051  0.197841   
6   reggae.00014.9.wav   66149          0.443945         0.088655  0.138845   
7   reggae.00024.2.wav   66149          0.346733         0.095444  0.126846   
8    metal.00030.3.wav   66149          0.444257         0.072107  0.217339   
9  country.00071.4.wav   66149          0.285375         0.083983  0.093730   

    rms_var  spectral_centroid_mean  spectral_centroid_var  \
0  0.007791             2156.231325          333455.342337   
1  0.002236             1439.715643           68955.697954   
2  0.001558             2049.831819          132030.817465   
3  0.001491             2237.056815          129862.001264   
4  0.000124             1775.591113           66645.168399   
5  0.002870             2214.610732          199935.538776   
6  0.007279             1484.512872          642910.324759   
7  0.003744             1305.636803          332459.613396   
8  0.001505             1421.397727          191302.733514   
9  0.001488             1202.917118          187703.629818   

   spectral_bandwidth_mean  spectral_bandwidth_var  ...  mfcc16_var  \
0              2295.327890           301528.295866  ...   36.512493   
1              1532.279764            78968.523547  ...   29.887444   
2              2043.472368            71699.726714  ...   29.158789   
3              2070.706749            62747.206984  ...   33.833458   
4              2351.155395            51753.800714  ...   48.042686   
5              2119.618559            59186.280529  ...   21.503252   
6              1964.079264           375077.067310  ...   50.773048   
7              1746.782088           187094.867915  ...  126.400932   
8              1825.933716           139859.687679  ...   18.040993   
9              1344.712469           125199.452661  ...   27.977787   

   mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  \
0     0.587634   44.336262     3.168914   31.690376     0.719836   50.416603   
1    -0.706779  105.123726     2.879812  157.346725     3.201282   71.674042   
2    -4.570374   24.995367    -0.735507   33.519482    -2.301054   38.444759   
3    -5.574619   29.497013     3.903063   18.930311    -2.205716   26.832264   
4    -3.686353   47.710155     3.593751   70.004326     0.011506   85.980957   
5    -8.433680   31.127623     1.954131   30.552839    -8.651063   24.572304   
6    -3.131397   49.980076     5.033700   64.940384    -1.773869   43.690498   
7    -1.566797   89.587677     2.702282  115.645538    -3.726380   35.156128   
8    -6.814065   17.995350    -4.847092   27.527098    -1.231671   19.959686   
9    -7.168938   44.668148    -3.637325   65.460632    -3.917785   53.857712   

   mfcc20_mean  mfcc20_var    label  
0    -3.192938   25.115688      pop  
1    -1.664307   53.640949     jazz  
2     6.482006   50.393089    disco  
3     0.551784   25.199505     rock  
4     1.892704  108.339722     jazz  
5     0.696554   26.691721    blues  
6    -1.714062   51.475685   reggae  
7    -1.981119   36.154800   reggae  
8     7.657926   19.391834    metal  
9    -7.813160   54.687420  country  

[10 rows x 60 columns]

In [ ]:
X.shape

(8991, 57)

In [ ]:
d = set(dataset['length'])
print(d)

{66149}


In [ ]:
dataset.describe()

length  chroma_stft_mean  chroma_stft_var     rms_mean       rms_var  \
count   8991.0       8991.000000      8991.000000  8991.000000  8.991000e+03   
mean   66149.0          0.379429         0.084906     0.131079  2.692355e-03   
std        0.0          0.090370         0.009649     0.068530  3.609881e-03   
min    66149.0          0.107108         0.015345     0.000953  4.379535e-08   
25%    66149.0          0.315718         0.079894     0.083768  6.191782e-04   
50%    66149.0          0.384857         0.085147     0.121635  1.496367e-03   
75%    66149.0          0.442305         0.091105     0.176834  3.168995e-03   
max    66149.0          0.749481         0.120964     0.442567  3.261522e-02   

       spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
count             8991.000000           8.991000e+03              8991.000000   
mean              2202.499294           4.180213e+05              2243.675807   
std                755.453076           4.368142e+05               546.167312   
min                472.741636           8.118813e+02               499.162910   
25%               1630.687076           1.232141e+05              1887.668895   
50%               2209.805128           2.666254e+05              2232.301304   
75%               2717.143710           5.636267e+05              2595.771961   
max               5432.534406           4.794119e+06              3708.147554   

       spectral_bandwidth_var  rolloff_mean  ...  mfcc16_mean   mfcc16_var  \
count            8.991000e+03   8991.000000  ...  8991.000000  8991.000000   
mean             1.182854e+05   4573.851725  ...     1.447258    49.903670   
std              1.015757e+05   1648.815846  ...     5.751630    33.659602   
min              1.183520e+03    658.336276  ...   -26.850016     1.325786   
25%              4.872991e+04   3385.889141  ...    -2.234193    29.608310   
50%              8.992711e+04   4636.595553  ...     1.488159    41.794029   
75%              1.587088e+05   5604.802903  ...     5.142493    59.088749   
max              1.235143e+06   9487.446477  ...    39.144405   683.932556   

       mfcc17_mean   mfcc17_var  mfcc18_mean   mfcc18_var  mfcc19_mean  \
count  8991.000000  8991.000000  8991.000000  8991.000000  8991.000000   
mean     -4.167124    52.012612     0.762790    52.587622    -2.493215   
std       5.697644    36.159784     5.191410    38.360354     5.127533   
min     -24.810783     1.624544   -20.733809     3.437439   -23.676704   
25%      -7.948629    29.862267    -2.445160    29.669745    -5.734310   
50%      -4.412789    42.266727     0.768402    41.915512    -2.699601   
75%      -0.697015    61.809235     3.902450    62.243496     0.516225   
max      34.048843   434.345642    36.970322   629.729797    31.365425   

        mfcc19_var  mfcc20_mean   mfcc20_var  
count  8991.000000  8991.000000  8991.000000  
mean     55.144385    -0.909010    57.501708  
std      41.979298     5.286712    46.882536  
min       3.065302   -35.640659     0.282131  
25%      30.503081    -4.015092    30.086961  
50%      43.447445    -1.033373    44.516968  
75%      65.669441     2.218058    68.463200  
max    1143.230591    34.212101   910.473206  

[8 rows x 58 columns]

In [ ]:
dataset['label'].isna().sum()

0

In [ ]:
print(X)

[[ 4.64263797e-01  7.97443986e-02  2.28116170e-01 ...  5.04166031e+01
  -3.19293833e+00  2.51156883e+01]
 [ 2.54603684e-01  9.01146606e-02  7.59600848e-02 ...  7.16740417e+01
  -1.66430664e+00  5.36409492e+01]
 [ 4.88070458e-01  6.59425855e-02  1.19709320e-01 ...  3.84447594e+01
   6.48200607e+00  5.03930893e+01]
 ...
 [ 2.91293383e-01  8.83856714e-02  1.49194658e-01 ...  2.93074741e+01
  -6.44086599e+00  7.03473892e+01]
 [ 2.49858931e-01  8.92840847e-02  1.30065471e-01 ...  7.03442841e+01
  -7.93861914e+00  8.18951492e+01]
 [ 3.32883388e-01  9.25975665e-02  1.00225195e-01 ...  8.79597168e+01
  -7.27754116e+00  3.67118073e+01]]


In [ ]:
print(y)

['pop' 'jazz' 'disco' ... 'country' 'blues' 'country']


In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
X_scaled.shape

(8991, 57)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)

In [ ]:
pca.fit(X_scaled)

PCA(n_components=2)

In [ ]:
pca_data = pca.transform(X_scaled)
pca_data.shape

(8991, 2)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(pca_data, y, test_size = 0.2, random_state = 0)

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [ ]:
rf_classifier = RandomForestClassifier(n_estimators=800,random_state=87)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=800, random_state=87)

In [ ]:
y_pred = rf_classifier.predict(X_test)
print(y_pred)

['metal' 'classical' 'blues' ... 'reggae' 'classical' 'rock']


In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
encoded_target = label_encoder.fit_transform(y_pred)
print(encoded_target)

[6 1 0 ... 8 1 9]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

[[122   4  13   3   1   6   6   0   5   3]
 [  1 151   2   0   0  14   0   0   1   2]
 [ 21   4 134  15   0  11   2   3   6   9]
 [  7   1   7 117   5   5   6  12  12  15]
 [  5   0   4  10 117   0   4  10  14   3]
 [  6  15  10   0   0 141   1   3   2   1]
 [  1   1   0   6   1   1 149   0   1   6]
 [  0   0   5   8   8   4   0 167   8   3]
 [  6   0   5   5   4   6   0   4 153   1]
 [  5   2  10   8   1  10  10   3   6 119]]
Accuracy: 0.7615341856586992


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [ ]:
classifier = KNeighborsClassifier(n_neighbors = 8, metric = 'manhattan', p = 1)
classifier.fit(X_train, y_train)

KNeighborsClassifier(metric='manhattan', n_neighbors=8, p=1)

In [ ]:
y_pred = classifier.predict(X_test)
print(y_pred)

['metal' 'classical' 'jazz' ... 'country' 'jazz' 'disco']


In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
encoded_target = label_encoder.fit_transform(y_pred)
print(encoded_target)

[6 1 5 ... 2 5 3]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

[[ 50  14  20  10   4  19  29   1   7   9]
 [  8 134   5   2   1  21   0   0   0   0]
 [ 46  18  36  22   6  25   7   3  20  22]
 [ 18   2  27  48  22   4  17  13  21  15]
 [  9   0   9  30  50   1  17  32  13   6]
 [ 27  42  22   7   8  52   1   1   5  14]
 [  6   2   8  11   4   1 118   2   2  12]
 [  8   0   7  22  51   1   0  92  20   2]
 [ 13   1  25  19  22   4   6  12  77   5]
 [ 27   4  23  28  10  14  25   2  18  23]]
Accuracy: 0.3779877709838799


In [ ]:
import pandas as pd

# Load the test data (replace 'test_data.csv' with the actual file path)
test_data = pd.read_csv('/content/test.csv')

id = test_data['id']

# Do you pre-processing as required
test_X = test_data.iloc[:,1:-1].values
print(test_X)


[[ 3.52453470e-01  7.90736973e-02  4.97621968e-02 ...  4.75594788e+01
  -1.05313311e+01  4.00155067e+01]
 [ 4.78755862e-01  8.78170878e-02  1.61004096e-01 ...  8.33233643e+01
   1.57252729e+00  5.99160576e+01]
 [ 3.29632014e-01  7.66692981e-02  1.91605970e-01 ...  3.33445282e+01
  -1.86141944e+00  3.92168388e+01]
 ...
 [ 2.09669456e-01  9.21973139e-02  4.56145518e-02 ...  9.11641006e+01
  -9.53362751e+00  7.99514313e+01]
 [ 3.93055648e-01  7.95776546e-02  7.72661492e-02 ...  2.73242550e+01
   5.86014688e-01  3.20449257e+01]
 [ 2.01501265e-01  9.14067701e-02  1.14103124e-01 ...  1.46409180e+02
  -4.74680090e+00  9.78776016e+01]]


In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(test_X)

In [ ]:
predictions = classifier.predict(X_scaled)
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
encoded_target = label_encoder.fit_transform(predictions)

In [ ]:
submission_df = pd.DataFrame({'id': id,  'label': encoded_target})

# Save the submission DataFrame to a CSV file
submission_df.to_csv('submissions.csv', index=False)